apiVersion: v1
entries:
  fluvio-core:
  - apiVersion: v2
    created: "2020-06-01T14:56:47.186591-07:00"
    description: A Helm chart for Fluvio
    digest: d753c39c6e5ea742c8182b02456a6e6ae1117a1f2ed1339903c7e9f66605c6f9
    name: fluvio-core
    type: application
    urls:
    - fluvio-core-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    created: "2020-06-01T14:56:47.186259-07:00"
    description: A Helm chart for Fluvio
    digest: e76b6bb68b991ff333264dcd74fde4398430c1be27530760abee2c3cee321c83
    name: fluvio-core
    type: application
    urls:
    - fluvio-core-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    created: "2020-06-01T14:56:47.185091-07:00"
    description: A Helm chart for Fluvio
    digest: 545fceb66b3d3045dc355c3e8fd98d15e03579d7a94965d48b41aa217af7e0af
    name: fluvio-core
    type: application
    urls:
    - fluvio-core-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2020-06-01T14:56:47.184491-07:00"
    description: A Helm chart for Fluvio
    digest: f0cd59694da447ccc185b6b497eec65b9e5bc2a94ef83c25b444339a4047d102
    name: fluvio-core
    type: application
    urls:
    - fluvio-core-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.2.3
    created: "2020-06-01T14:56:47.183872-07:00"
    description: A Helm chart for Fluvio
    digest: bb21f4de71bd3525c4a0a614e645a2d24ed96f55e8c10426ec9ce55ee133d2c7
    name: fluvio-core
    type: application
    urls:
    - fluvio-core-0.2.3.tgz
    version: 0.2.3
  fluvio-sys:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-06-01T14:56:47.187189-07:00"
    description: A Helm chart for Fluvio system components
    digest: 55cd07dbf440277c854814c589d1098070bc633b52bb044079a2288b0ae53cc3
    name: fluvio-sys
    type: application
    urls:
    - fluvio-sys-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-01T14:56:47.181347-07:00"
