apiVersion: v1
entries:
  fluvio:
  - apiVersion: v2
    appVersion: 0.2.3
    created: "2020-02-06T23:24:16.312798-08:00"
    description: A Helm chart for Fluvio
    digest: c36ed217ac0798d9b6caf7fc4fa7ca92347f5be59a3edf5a1a8b5325c01d1d4e
    name: fluvio
    type: application
    urls:
    - fluvio-0.2.3.tgz
    version: 0.2.3
generated: "2020-02-06T23:24:16.31152-08:00"
